EductionWebSite/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Eduction.Data;
using EductionWeb.Areas.Admin.Models;
using Eduction.Service.Catalog.Category;
using Eduction.Service.DTOs.Category;


namespace EductionWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : AdminController
    {

        #region field
        private readonly ICategoryService _categoryService = null;

        public CategoryController(ICategoryService categoryService)
        {

            _categoryService = categoryService;
        }
        #endregion
        public IActionResult Index()
        {
            return RedirectToAction("List");

        }
        [HttpGet]
        public async Task<IActionResult> List(CategoryListItemDTO dTO)
        {

            return View(await _categoryService.SearchCategoryAsync(dTO.CategorySearchName));
        }
        [HttpGet]
        public async Task<IActionResult> GetCategory(string CategorySearchName)
        {
            var _list = await _categoryService.SearchCategoryAsync(CategorySearchName);     
            var list = _list.categories.ToList();
            return new ObjectResult(list);
        }
        [HttpGet]
        public async Task<IActionResult> Create(int? id)
        {
            CategoryDTO DTO = new CategoryDTO();
            var Category = await _categoryService.SearchCategoryByIdAsync(id);
            if (Category != null)
                DTO = await _categoryService.SearchCategoryByIdAsync(id);           
            return View(DTO);
        }
        [HttpGet]
        public async Task<IActionResult> ModalCreate(int? id)
        {          
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CategoryDTO DTO)
        {
            if (!ModelState.IsValid)
                return View(DTO);
            if (DTO.ID != 0)
                await _categoryService.UpdateCategoryAsync(DTO);
            else
                await _categoryService.RegisterCategoryAsync(DTO);
            return RedirectToAction("List");
        }
        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            await _categoryService.RemoveCategoryAsync(id);
            return Ok();
        }
    }
}

EductionWebSite/Areas/Admin/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Eduction.Core.Domains;
using Eduction.Data;
using Eduction.Service.DTOs.Customer;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EductionWeb.Areas.Admin.Controllers
{
    public class CustomerController : AdminController
    {
        #region Fileds
        private readonly UserManager<Customer> userManager;
        private readonly RoleManager<CustomerRole> roleManager;
        private readonly SqlServerApplicationContext context;

        public CustomerController(UserManager<Customer> userManager, RoleManager<CustomerRole> roleManager, SqlServerApplicationContext context)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.context = context;
        }

        #endregion

        public IActionResult Index()
        {
            return Redirect("/Admin/Customer/List");
        }
        [HttpGet]
        public IActionResult List()
        {
            var users = userManager.Users.ToList();
            List<CustomerRegisterDTO> model = new List<CustomerRegisterDTO>();
            foreach (var item in users)
            {
                model.Add(new CustomerRegisterDTO()
                {
                    Email = item.Email,
                    FirstName = item.FirstName,
                    LastName = item.LastName,
                    Id = item.Id,
                    UserName = item.UserName
                });
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> ManageRoles(int id)
        {
            var user = await userManager.FindByIdAsync(id.ToString());

            var model = new ManageCustomeRoleModel();

            model.fullName = user.FirstName + " " + user.LastName;
            model.Id = user.Id.ToString();

            model.ListRoles = roleManager.Roles.ToList();

            foreach (var item in model.ListRoles)
            {
                if (await userManager.IsInRoleAsync(user, item.Name))
                {
                    model.AssignedRoles.Add(item);

                }
            }

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> SaveRole(string roleids, string userid)
        {
            if (roleids == null)
                return Ok();

            var listids = roleids.Split(";");
            var user = await userManager.FindByIdAsync(userid.ToString());
            var ListRoles = roleManager.Roles.ToList();
            foreach (var item in ListRoles)
            {

                if (listids.Contains(item.Id.ToString()))
                    await userManager.AddToRoleAsync(user, item.Name);
                else
                {

                    await userManager.RemoveFromRoleAsync(user, item.Name);
                }

            }
            return Ok();
        }
    }
}

EductionWebSite/Areas/Admin/Views/Customer/List.cshtml
@model List<Eduction.Service.DTOs.Customer.CustomerRegisterDTO>
@{
        Layout = "~/Areas/Admin/Views/Shared/_layout.cshtml";
}

<div>
    <caption-view asp-title="لیست مشتریان "></caption-view>

    <div style="text-align:left">
        <a class="btn-link" asp-area="Admin" asp-controller="Customer" asp-action="Create">ثبت جدید</a>
    </div>
    <br />
    <table class="table text-center table-bordered table-hover">
        <thead>
            <tr>
                <td>نام و نام خانوادگی</td>
                <td>کلمه کاربری</td>
                <td>پست الکترونیکی</td>
                <td>تخصیص نقش</td>
                <td>ویرایش</td>
                <td>حذف</td>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                var spec = item.FirstName + " " + item.LastName;
                <tr>
                    <td>@spec</td>
                    <td>@item.UserName</td>
                    <td>@item.Email</td>
                    <td><a class="btn-link" asp-area="Admin" asp-controller="Customer" asp-action="ManageRoles" asp-route-id="@item.Id">تخصیص</a></td>
                    <td><a class="btn-link" asp-area="Admin" asp-controller="Category" asp-action="Create" asp-route-id="@item.Id">ویرایش</a></td>
                    <td><a class="btn-link" asp-area="Admin" asp-controller="Category" asp-action="Remove" asp-route-id="@item.Id">حذف</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

EductionWebSite/Areas/Admin/Views/Customer/ManageRoles.cshtml
@model Eduction.Service.DTOs.Customer.ManageCustomeRoleModel;
@{
    Layout = "~/Areas/Admin/Views/Shared/_layout.cshtml";
}


<div>
    @{ var des = "مدیریت نقش" + " " + Model.fullName;}
    <caption-view asp-title="@des"></caption-view>
    <div id="divrole" class="form-group">
        @foreach (var item in Model.ListRoles)
        {
            <div class="form-group form-check">
                <label class="form-check-label">
                    @if (Model.AssignedRoles.Contains(item))
                    {
                        <input class="form-check-input" id="@item.Id" type="checkbox" checked="checked"> @item.Name

                    }
                    else
                    {
                        <input class="form-check-input" id="@item.Id" type="checkbox"> @item.Name
                    }
                </label>
            </div>
        }
        <button onclick="saveroleuser()" class="btn btn-dark"><i class="fa fa-save"></i>ذخیره</button>
    </div>

</div>
<script>
    function saveroleuser() {

        var roleids = "";
        $("#divrole input[type='checkbox']").each(function () {
            if ($(this).is(":checked")) {
                roleids += $(this).attr("id")+";";
            }

        });


        AJX.post("/Admin/Customer/SaveRole", { roleids: roleids, userid:@Model.Id }, function () {

            alert("اطلاعات با موفقیت ذخیره شده");
        });
    }
</script>